### ISSUE TITLE
Erreur lorsque l'on demande a creer un directory

### ISSUE THREAD

**Issue by Nyaleph** [tagadanar/leekwars_gardener#6]
De plus j'ai remarqué que dir_path n'est pas utilisé dans api.creat_dir

```
Traceback (most recent call last):
  File "/home/nyaleph/Documents/leekwars/leekwars_gardener/main.py", line 152, in <module>
    main()
  File "/home/nyaleph/Documents/leekwars/leekwars_gardener/main.py", line 84, in main
    todo.trySynchronize()
  File "/home/nyaleph/Documents/leekwars/leekwars_gardener/todolist.py", line 202, in trySynchronize
    self.recursiv_read(ais, g.LW_ROOT_DIR, directory, ignored)
  File "/home/nyaleph/Documents/leekwars/leekwars_gardener/todolist.py", line 217, in recursiv_read
    folder_id = self.api.create_dir(dir_path, name, dir_id, lw_item)
  File "/home/nyaleph/Documents/leekwars/leekwars_gardener/lwapi.py", line 255, in create_dir
    print("%s%s%s when trying to create directory %s%s%s"%(bcolors.FAIL,r.json()['error'],bcolors.ENDC,bcolors.HEADER,dir_name,bcolors.ENDC))
  File "/home/nyaleph/.local/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py",line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py",line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tagadanar** [comment]
Ok merci du retour, je vais regarder ça ^^
